.PHONY: clean All

All:
	@echo "----------Building project:[ microcomputer - Debug ]----------"
	@cd "microcomputer" && $(MAKE) -f  "microcomputer.mk"
clean:
	@echo "----------Cleaning project:[ microcomputer - Debug ]----------"
	@cd "microcomputer" && $(MAKE) -f  "microcomputer.mk" clean
