.PHONY: clean All

All:
	@echo "----------Building project:[ console - Debug ]----------"
	@cd "console" && $(MAKE) -f  "console.mk"
clean:
	@echo "----------Cleaning project:[ console - Debug ]----------"
	@cd "console" && $(MAKE) -f  "console.mk" clean
